[package]
name = "count-range-sketch"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.1"
slotmap = "1"
replace_with = "0.1"
get-size2 = "0.6.2"
equivalent = "1"

[dev-dependencies]
rand = "0.9"
proptest = "1.7.0"

[profile.release]
debug-assertions = true
